
#user  nobody;
worker_processes  1;

#error_log  logs/error.log;
#error_log  logs/error.log  notice;
#error_log  logs/error.log  info;

#pid        logs/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout  65;

    server {
        listen       5200;
        server_name  localhost;

        location / {
            root   html;
            index  index.html;
        }

        location /api {
            proxy_pass http://localhost:1086;
        }
    }

}
